// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/openchami/boot-service/apis/boot.openchami.io/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.BMC{}); err != nil {
		return fmt.Errorf("failed to register BMC: %w", err)
	}
	if err := gen.RegisterResource(&v1.BootConfiguration{}); err != nil {
		return fmt.Errorf("failed to register BootConfiguration: %w", err)
	}
	if err := gen.RegisterResource(&v1.Node{}); err != nil {
		return fmt.Errorf("failed to register Node: %w", err)
	}

	return nil
}
