// Code generated by Fabrica dev. DO NOT EDIT.
// Template: cmd/fabrica/generate.go:generateVersionedRegistrationCode
// Generated: 2026-04-25T13:37:22Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/openchami/boot-service/apis/boot.openchami.io/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.BMC{}); err != nil {
		return fmt.Errorf("failed to register BMC: %w", err)
	}
	if err := gen.RegisterResource(&v1.BootConfiguration{}); err != nil {
		return fmt.Errorf("failed to register BootConfiguration: %w", err)
	}
	if err := gen.RegisterResource(&v1.Node{}); err != nil {
		return fmt.Errorf("failed to register Node: %w", err)
	}

	return nil
}
