// Code generated by fabrica codegen init. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/alexlovelltroy/fabrica/pkg/codegen"
	"github.com/openchami/boot-service/pkg/resources/bootconfiguration"
	"github.com/openchami/boot-service/pkg/resources/node"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica codegen init' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&bootconfiguration.BootConfiguration{}); err != nil {
		return fmt.Errorf("failed to register BootConfiguration: %w", err)
	}
	if err := gen.RegisterResource(&node.Node{}); err != nil {
		return fmt.Errorf("failed to register Node: %w", err)
	}

	return nil
}
