// Code generated by Fabrica 0.3.0. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for BMC resources.
// Generated from: pkg/codegen/templates/handlers.go.tmpl
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /bmcs (list all bmcs)
//   - GET /bmcs/{uid} (get specific BMC)
//   - POST /bmcs (create new BMC)
//   - PUT /bmcs/{uid} (update BMC spec)
//   - PATCH /bmcs/{uid} (patch BMC spec)
//   - DELETE /bmcs/{uid} (delete BMC)
//   - PUT /bmcs/{uid}/status (update BMC status)
//   - PATCH /bmcs/{uid}/status (patch BMC status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadBMC*/SaveBMC*/DeleteBMC*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/bmc/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadBMCWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/boot-service/internal/storage"
	"github.com/openchami/boot-service/pkg/resources/bmc"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
)

// GetBMCs returns all BMC resources
func GetBMCs(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bmcs, err := storage.LoadAllBMCs(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load bmcs: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bmcs)
}

// GetBMC returns a specific BMC resource by UID
func GetBMC(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMC UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadBMC() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bMC, err := storage.LoadBMC(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMC not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bMC)
}

// CreateBMC creates a new BMC resource
func CreateBMC(w http.ResponseWriter, r *http.Request) {
	var req CreateBMCRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("BMC")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	bMC := &bmc.BMC{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "BMC",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.BMCSpec,
	}

	bMC.Metadata.Initialize(req.Name, uid)

	// Set labels and annotations
	for k, v := range req.Labels {
		bMC.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		bMC.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(bMC); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), bMC); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveBMC(r.Context(), bMC); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BMC: %w", err))
		return
	}

	// Publish resource created event
	if err := events.PublishResourceCreated(r.Context(), "BMC", bMC.GetUID(), bMC.GetName(), bMC); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for BMC %s: %v\n", bMC.GetUID(), err)
	}

	respondJSON(w, http.StatusCreated, bMC)
}

// UpdateBMC updates the spec of an existing BMC resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //bmcs/{uid}/status to update status.
func UpdateBMC(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMC UID is required"))
		return
	}

	bMC, err := storage.LoadBMC(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMC not found: %w", err))
		return
	}

	var req UpdateBMCRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		bMC.SetName(req.Name)
	}

	// Update spec fields ONLY - status should use /status subresource
	bMC.Spec = req.BMCSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		bMC.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		bMC.SetAnnotation(k, v)
	}

	bMC.Touch()

	if err := storage.SaveBMC(r.Context(), bMC); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BMC: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": bMC.Metadata.UpdatedAt,
	}
	if err := events.PublishResourceUpdated(r.Context(), "BMC", bMC.GetUID(), bMC.GetName(), bMC, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for BMC %s: %v\n", bMC.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, bMC)
}

// PatchBMC patches an existing BMC resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchBMC(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMC UID is required"))
		return
	}

	bMC, err := storage.LoadBMC(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMC not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(bMC.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &bMC.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata
	bMC.Touch()

	// Save the patched resource
	if err := storage.SaveBMC(r.Context(), bMC); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BMC: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": bMC.Metadata.UpdatedAt,
	}
	if err := events.PublishResourcePatched(r.Context(), "BMC", bMC.GetUID(), bMC.GetName(), bMC, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for BMC %s: %v\n", bMC.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, bMC)
}

// UpdateBMCStatus updates only the status of a BMC resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateBMCStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMC UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadBMC(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMC not found: %w", err))
		return
	}

	var statusUpdate bmc.BMCStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate
	res.Touch()

	if err := storage.SaveBMC(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BMC status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourceUpdated(r.Context(), "BMC", res.GetUID(), res.GetName(), res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for BMC %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// PatchBMCStatus patches only the status of a BMC resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchBMCStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMC UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadBMC(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMC not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Touch()

	if err := storage.SaveBMC(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BMC status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourcePatched(r.Context(), "BMC", res.GetUID(), res.GetName(), res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for BMC %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteBMC deletes a BMC resource
func DeleteBMC(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMC UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	bMC, err := storage.LoadBMC(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMC not found: %w", err))
		return
	}

	if err := storage.DeleteBMC(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete BMC: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}
	if err := events.PublishResourceDeleted(r.Context(), "BMC", bMC.GetUID(), bMC.GetName(), deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for BMC %s: %v\n", bMC.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "BMC deleted successfully",
		UID:     uid,
	})
}
