// Code generated by Fabrica 0.3.0. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for BootConfiguration resources.
// Generated from: pkg/codegen/templates/handlers.go.tmpl
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /bootconfigurations (list all bootconfigurations)
//   - GET /bootconfigurations/{uid} (get specific BootConfiguration)
//   - POST /bootconfigurations (create new BootConfiguration)
//   - PUT /bootconfigurations/{uid} (update BootConfiguration spec)
//   - PATCH /bootconfigurations/{uid} (patch BootConfiguration spec)
//   - DELETE /bootconfigurations/{uid} (delete BootConfiguration)
//   - PUT /bootconfigurations/{uid}/status (update BootConfiguration status)
//   - PATCH /bootconfigurations/{uid}/status (patch BootConfiguration status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadBootConfiguration*/SaveBootConfiguration*/DeleteBootConfiguration*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/bootconfiguration/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadBootConfigurationWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/boot-service/internal/storage"
	"github.com/openchami/boot-service/pkg/resources/bootconfiguration"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
)

// GetBootConfigurations returns all BootConfiguration resources
func GetBootConfigurations(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bootconfigurations, err := storage.LoadAllBootConfigurations(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load bootconfigurations: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bootconfigurations)
}

// GetBootConfiguration returns a specific BootConfiguration resource by UID
func GetBootConfiguration(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BootConfiguration UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadBootConfiguration() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bootConfiguration, err := storage.LoadBootConfiguration(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BootConfiguration not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bootConfiguration)
}

// CreateBootConfiguration creates a new BootConfiguration resource
func CreateBootConfiguration(w http.ResponseWriter, r *http.Request) {
	var req CreateBootConfigurationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("BootConfiguration")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	bootConfiguration := &bootconfiguration.BootConfiguration{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "BootConfiguration",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.BootConfigurationSpec,
	}

	bootConfiguration.Metadata.Initialize(req.Name, uid)

	// Set labels and annotations
	for k, v := range req.Labels {
		bootConfiguration.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		bootConfiguration.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(bootConfiguration); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), bootConfiguration); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveBootConfiguration(r.Context(), bootConfiguration); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BootConfiguration: %w", err))
		return
	}

	// Publish resource created event
	if err := events.PublishResourceCreated(r.Context(), "BootConfiguration", bootConfiguration.GetUID(), bootConfiguration.GetName(), bootConfiguration); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for BootConfiguration %s: %v\n", bootConfiguration.GetUID(), err)
	}

	respondJSON(w, http.StatusCreated, bootConfiguration)
}

// UpdateBootConfiguration updates the spec of an existing BootConfiguration resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //bootconfigurations/{uid}/status to update status.
func UpdateBootConfiguration(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BootConfiguration UID is required"))
		return
	}

	bootConfiguration, err := storage.LoadBootConfiguration(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BootConfiguration not found: %w", err))
		return
	}

	var req UpdateBootConfigurationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		bootConfiguration.SetName(req.Name)
	}

	// Update spec fields ONLY - status should use /status subresource
	bootConfiguration.Spec = req.BootConfigurationSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		bootConfiguration.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		bootConfiguration.SetAnnotation(k, v)
	}

	bootConfiguration.Touch()

	if err := storage.SaveBootConfiguration(r.Context(), bootConfiguration); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BootConfiguration: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": bootConfiguration.Metadata.UpdatedAt,
	}
	if err := events.PublishResourceUpdated(r.Context(), "BootConfiguration", bootConfiguration.GetUID(), bootConfiguration.GetName(), bootConfiguration, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for BootConfiguration %s: %v\n", bootConfiguration.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, bootConfiguration)
}

// PatchBootConfiguration patches an existing BootConfiguration resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchBootConfiguration(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BootConfiguration UID is required"))
		return
	}

	bootConfiguration, err := storage.LoadBootConfiguration(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BootConfiguration not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(bootConfiguration.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &bootConfiguration.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata
	bootConfiguration.Touch()

	// Save the patched resource
	if err := storage.SaveBootConfiguration(r.Context(), bootConfiguration); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BootConfiguration: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": bootConfiguration.Metadata.UpdatedAt,
	}
	if err := events.PublishResourcePatched(r.Context(), "BootConfiguration", bootConfiguration.GetUID(), bootConfiguration.GetName(), bootConfiguration, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for BootConfiguration %s: %v\n", bootConfiguration.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, bootConfiguration)
}

// UpdateBootConfigurationStatus updates only the status of a BootConfiguration resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateBootConfigurationStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BootConfiguration UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadBootConfiguration(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BootConfiguration not found: %w", err))
		return
	}

	var statusUpdate bootconfiguration.BootConfigurationStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate
	res.Touch()

	if err := storage.SaveBootConfiguration(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BootConfiguration status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourceUpdated(r.Context(), "BootConfiguration", res.GetUID(), res.GetName(), res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for BootConfiguration %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// PatchBootConfigurationStatus patches only the status of a BootConfiguration resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchBootConfigurationStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BootConfiguration UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadBootConfiguration(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BootConfiguration not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Touch()

	if err := storage.SaveBootConfiguration(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BootConfiguration status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourcePatched(r.Context(), "BootConfiguration", res.GetUID(), res.GetName(), res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for BootConfiguration %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteBootConfiguration deletes a BootConfiguration resource
func DeleteBootConfiguration(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BootConfiguration UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	bootConfiguration, err := storage.LoadBootConfiguration(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BootConfiguration not found: %w", err))
		return
	}

	if err := storage.DeleteBootConfiguration(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete BootConfiguration: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}
	if err := events.PublishResourceDeleted(r.Context(), "BootConfiguration", bootConfiguration.GetUID(), bootConfiguration.GetName(), deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for BootConfiguration %s: %v\n", bootConfiguration.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "BootConfiguration deleted successfully",
		UID:     uid,
	})
}
