// Code generated by Fabrica v0.4.7-3-g374fc28 (commit: 374fc28). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains request/response models for REST API operations.
// Generated from: pkg/codegen/templates/models.go.tmpl
//
// To modify request/response models:
//  1. Edit the template file: pkg/codegen/templates/models.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated models for each resource:
//   - ResourceResponse: Single resource response (alias to resource type)
//   - ResourcesResponse: List of resources with pagination info
//   - CreateResourceRequest: Create operation request body
//   - UpdateResourceRequest: Update operation request body
//   - DeleteResponse: Delete operation response
//
// Request structure:
//   - Embeds resource Spec fields inline (json:",inline")
//   - Includes metadata fields (Name, Labels, Annotations)
//   - Uses validation tags for required fields
//
// To add custom validation:
//  1. Add validation tags to template (e.g., validate:"required,email")
//  2. Implement validation middleware in handlers
//
// To add additional fields:
//  1. Modify Create/Update request structs in template
//  2. Update corresponding handlers to process new fields
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/openchami/fabrica/pkg/fabrica"

	"github.com/openchami/boot-service/apis/boot.openchami.io/v1"
)

// BMCResponse represents the response for BMC operations
type BMCResponse = v1.BMC

// CreateBMCRequest represents a request to create a BMC
type CreateBMCRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.BMCSpec        `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateBMCRequest) AsSpec() v1.BMCSpec {
	return r.Spec
}

// UpdateBMCRequest represents a request to update a BMC
type UpdateBMCRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.BMCSpec        `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateBMCRequest) AsSpec() v1.BMCSpec {
	return r.Spec
}

// BootConfigurationResponse represents the response for BootConfiguration operations
type BootConfigurationResponse = v1.BootConfiguration

// CreateBootConfigurationRequest represents a request to create a BootConfiguration
type CreateBootConfigurationRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.BootConfigurationSpec `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string        `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateBootConfigurationRequest) AsSpec() v1.BootConfigurationSpec {
	return r.Spec
}

// UpdateBootConfigurationRequest represents a request to update a BootConfiguration
type UpdateBootConfigurationRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.BootConfigurationSpec `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string        `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateBootConfigurationRequest) AsSpec() v1.BootConfigurationSpec {
	return r.Spec
}

// NodeResponse represents the response for Node operations
type NodeResponse = v1.Node

// CreateNodeRequest represents a request to create a Node
type CreateNodeRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.NodeSpec       `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateNodeRequest) AsSpec() v1.NodeSpec {
	return r.Spec
}

// UpdateNodeRequest represents a request to update a Node
type UpdateNodeRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.NodeSpec       `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateNodeRequest) AsSpec() v1.NodeSpec {
	return r.Spec
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message,omitempty"`
	Code    int    `json:"code,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}

// Helper functions for handlers

// respondJSON sends a JSON response
func respondJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(data); err != nil {
		http.Error(w, fmt.Sprintf("failed to encode response: %v", err), http.StatusInternalServerError)
	}
}

// respondError sends an error response
func respondError(w http.ResponseWriter, status int, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	response := ErrorResponse{
		Error: err.Error(),
		Code:  status,
	}
	json.NewEncoder(w).Encode(response)
}
