// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Node resources.
// Generated from: pkg/codegen/templates/handlers.go.tmpl
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /nodes (list all nodes)
//   - GET /nodes/{uid} (get specific Node)
//   - POST /nodes (create new Node)
//   - PUT /nodes/{uid} (update Node)
//   - DELETE /nodes/{uid} (delete Node)
//
// Authentication: DISABLED
// Storage: Uses storage.LoadNode*/SaveNode*/DeleteNode*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/node/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadNodeWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/alexlovelltroy/fabrica/pkg/resource"
	"github.com/alexlovelltroy/fabrica/pkg/validation"
	"github.com/alexlovelltroy/fabrica/pkg/versioning"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/boot-service/internal/storage"
	"github.com/openchami/boot-service/pkg/resources/node"
)

// GetNodes returns all Node resources
func GetNodes(w http.ResponseWriter, r *http.Request) {

	nodes, err := storage.LoadAllNodes()
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load nodes: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, nodes)
}

// GetNode returns a specific Node resource by UID
func GetNode(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadNode() with version-aware function

	node, err := storage.LoadNode(uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, node)
}

// CreateNode creates a new Node resource
func CreateNode(w http.ResponseWriter, r *http.Request) {
	var req CreateNodeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("Node")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	node := &node.Node{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "Node",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.NodeSpec,
	}

	node.Metadata.Initialize(req.Name, uid)

	// Set labels and annotations
	for k, v := range req.Labels {
		node.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		node.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(node); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), node); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveNode(node); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Node: %w", err))
		return
	}

	respondJSON(w, http.StatusCreated, node)
}

// UpdateNode updates an existing Node resource
func UpdateNode(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	node, err := storage.LoadNode(uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}

	var req UpdateNodeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		node.SetName(req.Name)
	}

	// Update spec fields - merge non-zero values from request
	node.Spec = req.NodeSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		node.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		node.SetAnnotation(k, v)
	}

	node.Touch()

	if err := storage.SaveNode(node); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Node: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, node)
}

// DeleteNode deletes a Node resource
func DeleteNode(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	if err := storage.DeleteNode(uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete Node: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "Node deleted successfully",
		UID:     uid,
	})
}
