// Code generated by Fabrica v0.4.4-12-ga94e778-dirty (commit: a94e778). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains OpenAPI 3.0 specification generation for all resources.
// Generated from: pkg/codegen/templates/server/openapi.go.tmpl
//
// To modify OpenAPI spec:
//  1. Edit the template file: pkg/codegen/templates/serveropenapi.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// OpenAPI endpoints:
//   - GET /openapi.json - Returns OpenAPI 3.0 spec
//   - GET /docs - Returns Swagger UI
//
// This file automatically generates OpenAPI schemas from Go types using
// kin-openapi's openapi3gen package. No docstring annotations required.
package main

import (
	"encoding/json"
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
	"github.com/openchami/boot-service/apis/boot.openchami.io/v1"
)

// ServeOpenAPISpec returns the OpenAPI 3.0 specification
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	spec := GenerateOpenAPISpec()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(spec); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeSwaggerUI returns the Swagger UI HTML page
func ServeSwaggerUI(w http.ResponseWriter, r *http.Request) {
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>boot_service API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; padding:0; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "/openapi.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// GenerateOpenAPISpec generates the complete OpenAPI 3.0 specification
func GenerateOpenAPISpec() *openapi3.T {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       "boot_service API",
			Description: "Fabrica-generated REST API with Kubernetes-style resource management",
			Version:     "1.0.0",
			Contact: &openapi3.Contact{
				Name: "Fabrica Project",
				URL:  "https://github.com/openchami/fabrica",
			},
		},
		Servers: openapi3.Servers{
			{
				URL:         "http://localhost:8080",
				Description: "Development server",
			},
		},
		Paths: openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas: make(openapi3.Schemas),
		},
	}

	// Register all resource paths
	registerBMCPaths(spec)
	registerBootConfigurationPaths(spec)
	registerNodePaths(spec)

	// Register /health endpoint
	healthOp := openapi3.NewOperation()
	healthOp.OperationID = "health"
	healthOp.Summary = "Service health"
	healthOp.Description = "Returns service health information"
	healthOp.Tags = []string{"Service"}
	healthResponseSchema := openapi3.NewObjectSchema().
		WithProperty("status", openapi3.NewStringSchema()).
		WithProperty("service", openapi3.NewStringSchema()).
		WithProperty("version", openapi3.NewStringSchema()).
		WithProperty("time", openapi3.NewStringSchema()).
		WithRequired([]string{"status"})
	healthExample := map[string]interface{}{
		"status":  "ok",
		"service": "boot_service",
		"version": "1.0.0",
		"time":    "2026-01-01T00:00:00Z",
	}
	healthResponseSchema.Example = healthExample
	healthOp.Responses = openapi3.NewResponses()
	healthOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Healthy").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: healthResponseSchema},
					Example: healthExample,
				},
			}),
	})
	spec.Paths.Set("/health", &openapi3.PathItem{Get: healthOp})

	// Register /openapi.json endpoint (self-referential spec endpoint)
	openAPIJsonOp := openapi3.NewOperation()
	openAPIJsonOp.OperationID = "getOpenAPISpec"
	openAPIJsonOp.Summary = "Get OpenAPI specification"
	openAPIJsonOp.Description = "Returns the complete OpenAPI 3.0 specification for this API"
	openAPIJsonOp.Tags = []string{"Service"}
	openAPIJsonOp.Responses = openapi3.NewResponses()
	openAPIJsonOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("OpenAPI specification").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema: &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()},
				},
			}),
	})
	spec.Paths.Set("/openapi.json", &openapi3.PathItem{Get: openAPIJsonOp})

	// Register /docs endpoint (Swagger UI)
	docsOp := openapi3.NewOperation()
	docsOp.OperationID = "getSwaggerUI"
	docsOp.Summary = "API documentation UI"
	docsOp.Description = "Returns an interactive Swagger UI for exploring the API"
	docsOp.Tags = []string{"Service"}
	docsOp.Responses = openapi3.NewResponses()
	docsOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Swagger UI HTML page").
			WithContent(map[string]*openapi3.MediaType{
				"text/html": {
					Schema: &openapi3.SchemaRef{Value: openapi3.NewStringSchema()},
				},
			}),
	})
	spec.Paths.Set("/docs", &openapi3.PathItem{Get: docsOp})

	// Register custom (non-Fabrica-generated) paths.
	// Defined in openapi_extensions.go – safe to edit, never overwritten.
	registerCustomOpenAPIPaths(spec)

	return spec
}

// registerBMCPaths registers OpenAPI paths for BMC resources
func registerBMCPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.BMC{}, spec.Components.Schemas)
	spec.Components.Schemas["BMC"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateBMCRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateBMCRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateBMCRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateBMCRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.BMCStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["BMCStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List BMCs operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listBMCs"
	listOp.Summary = "List all BMC resources"
	listOp.Description = "Returns a list of all BMC resources in the inventory"
	listOp.Tags = []string{"BMC"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/BMC"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create BMC operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createBMC"
	createOp.Summary = "Create a new BMC resource"
	createOp.Description = "Creates a new BMC resource with the provided specification"
	createOp.Tags = []string{"BMC"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateBMCRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BMC",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get BMC operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getBMC"
	getOp.Summary = "Get a specific BMC resource"
	getOp.Description = "Returns details of a specific BMC resource by UID"
	getOp.Tags = []string{"BMC"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BMC",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update BMC operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateBMC"
	updateOp.Summary = "Update a BMC resource"
	updateOp.Description = "Updates an existing BMC resource with new values"
	updateOp.Tags = []string{"BMC"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateBMCRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BMC",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch BMC operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchBMC"
	patchOp.Summary = "Patch a BMC resource"
	patchOp.Description = "Partially updates an existing BMC resource using patch semantics"
	patchOp.Tags = []string{"BMC"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BMC",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update BMC status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateBMCStatus"
	updateStatusOp.Summary = "Update BMC status"
	updateStatusOp.Description = "Updates only the status subresource for an existing BMC"
	updateStatusOp.Tags = []string{"BMC"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BMCStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BMC"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch BMC status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchBMCStatus"
	patchStatusOp.Summary = "Patch BMC status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing BMC"
	patchStatusOp.Tags = []string{"BMC"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BMC"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete BMC operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteBMC"
	deleteOp.Summary = "Delete a BMC resource"
	deleteOp.Description = "Removes a BMC resource from the inventory"
	deleteOp.Tags = []string{"BMC"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the BMC resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/bmcs", collectionPath)
	spec.Paths.Set("/bmcs/{uid}", itemPath)
	spec.Paths.Set("/bmcs/{uid}/status", statusPath)
}

// registerBootConfigurationPaths registers OpenAPI paths for BootConfiguration resources
func registerBootConfigurationPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.BootConfiguration{}, spec.Components.Schemas)
	spec.Components.Schemas["BootConfiguration"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateBootConfigurationRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateBootConfigurationRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateBootConfigurationRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateBootConfigurationRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.BootConfigurationStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["BootConfigurationStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List BootConfigurations operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listBootConfigurations"
	listOp.Summary = "List all BootConfiguration resources"
	listOp.Description = "Returns a list of all BootConfiguration resources in the inventory"
	listOp.Tags = []string{"BootConfiguration"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/BootConfiguration"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create BootConfiguration operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createBootConfiguration"
	createOp.Summary = "Create a new BootConfiguration resource"
	createOp.Description = "Creates a new BootConfiguration resource with the provided specification"
	createOp.Tags = []string{"BootConfiguration"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateBootConfigurationRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootConfiguration",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get BootConfiguration operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getBootConfiguration"
	getOp.Summary = "Get a specific BootConfiguration resource"
	getOp.Description = "Returns details of a specific BootConfiguration resource by UID"
	getOp.Tags = []string{"BootConfiguration"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootConfiguration",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update BootConfiguration operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateBootConfiguration"
	updateOp.Summary = "Update a BootConfiguration resource"
	updateOp.Description = "Updates an existing BootConfiguration resource with new values"
	updateOp.Tags = []string{"BootConfiguration"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateBootConfigurationRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootConfiguration",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch BootConfiguration operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchBootConfiguration"
	patchOp.Summary = "Patch a BootConfiguration resource"
	patchOp.Description = "Partially updates an existing BootConfiguration resource using patch semantics"
	patchOp.Tags = []string{"BootConfiguration"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootConfiguration",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update BootConfiguration status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateBootConfigurationStatus"
	updateStatusOp.Summary = "Update BootConfiguration status"
	updateStatusOp.Description = "Updates only the status subresource for an existing BootConfiguration"
	updateStatusOp.Tags = []string{"BootConfiguration"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BootConfigurationStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BootConfiguration"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch BootConfiguration status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchBootConfigurationStatus"
	patchStatusOp.Summary = "Patch BootConfiguration status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing BootConfiguration"
	patchStatusOp.Tags = []string{"BootConfiguration"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BootConfiguration"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete BootConfiguration operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteBootConfiguration"
	deleteOp.Summary = "Delete a BootConfiguration resource"
	deleteOp.Description = "Removes a BootConfiguration resource from the inventory"
	deleteOp.Tags = []string{"BootConfiguration"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the BootConfiguration resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/bootconfigurations", collectionPath)
	spec.Paths.Set("/bootconfigurations/{uid}", itemPath)
	spec.Paths.Set("/bootconfigurations/{uid}/status", statusPath)
}

// registerNodePaths registers OpenAPI paths for Node resources
func registerNodePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.Node{}, spec.Components.Schemas)
	spec.Components.Schemas["Node"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateNodeRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateNodeRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateNodeRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateNodeRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.NodeStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["NodeStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List Nodes operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listNodes"
	listOp.Summary = "List all Node resources"
	listOp.Description = "Returns a list of all Node resources in the inventory"
	listOp.Tags = []string{"Node"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/Node"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create Node operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createNode"
	createOp.Summary = "Create a new Node resource"
	createOp.Description = "Creates a new Node resource with the provided specification"
	createOp.Tags = []string{"Node"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateNodeRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get Node operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getNode"
	getOp.Summary = "Get a specific Node resource"
	getOp.Description = "Returns details of a specific Node resource by UID"
	getOp.Tags = []string{"Node"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update Node operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateNode"
	updateOp.Summary = "Update a Node resource"
	updateOp.Description = "Updates an existing Node resource with new values"
	updateOp.Tags = []string{"Node"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateNodeRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch Node operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchNode"
	patchOp.Summary = "Patch a Node resource"
	patchOp.Description = "Partially updates an existing Node resource using patch semantics"
	patchOp.Tags = []string{"Node"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update Node status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateNodeStatus"
	updateStatusOp.Summary = "Update Node status"
	updateStatusOp.Description = "Updates only the status subresource for an existing Node"
	updateStatusOp.Tags = []string{"Node"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/NodeStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Node"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch Node status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchNodeStatus"
	patchStatusOp.Summary = "Patch Node status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing Node"
	patchStatusOp.Tags = []string{"Node"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Node"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete Node operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteNode"
	deleteOp.Summary = "Delete a Node resource"
	deleteOp.Description = "Removes a Node resource from the inventory"
	deleteOp.Tags = []string{"Node"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the Node resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/nodes", collectionPath)
	spec.Paths.Set("/nodes/{uid}", itemPath)
	spec.Paths.Set("/nodes/{uid}/status", statusPath)
}

func patchRequestBody() *openapi3.RequestBodyRef {
	patchSchema := &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()}
	return &openapi3.RequestBodyRef{
		Value: &openapi3.RequestBody{
			Required: true,
			Content: openapi3.Content{
				"application/merge-patch+json": &openapi3.MediaType{Schema: patchSchema},
				"application/json-patch+json":  &openapi3.MediaType{Schema: patchSchema},
				"application/shorthand-patch":  &openapi3.MediaType{Schema: patchSchema},
				"application/json":             &openapi3.MediaType{Schema: patchSchema},
			},
		},
	}
}

// Helper function for error responses
func errorResponse() *openapi3.ResponseRef {
	return &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Error response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ErrorResponse",
			}),
	}
}
