// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//  1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//
//	client, err := client.NewClient("http://localhost:8080", nil)
//	if err != nil {
//	    log.Fatal(err)
//	}
//
//	bmcs, err := client.GetBMCs(context.Background())
//	if err != nil {
//	    log.Fatal(err)
//	}
//
// To add authentication:
//  1. Create custom http.Client with auth transport
//  2. Pass it to NewClient:
//     httpClient := &http.Client{
//     Transport: &AuthTransport{Token: "your-token"},
//     }
//     client, _ := client.NewClient(baseURL, httpClient)
//
// To add custom headers:
//  1. Modify doRequest method to accept header options
//  2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//  1. Wrap http.Client with retry transport
//  2. Use github.com/hashicorp/go-retryablehttp or similar
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/openchami/boot-service/pkg/resources/bootconfiguration"
	"github.com/openchami/boot-service/pkg/resources/node"
	"io"
	"net/http"
	"net/url"
	"path"
)

// Client provides access to the inventory API
type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
	version    string // Optional API version for Accept/Content-Type headers
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:    c.baseURL,
		httpClient: c.httpClient,
		version:    version,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// GetBootConfigurations retrieves all bootconfigurations
func (c *Client) GetBootConfigurations(ctx context.Context) ([]bootconfiguration.BootConfiguration, error) {
	var response []bootconfiguration.BootConfiguration
	if err := c.doRequest(ctx, "GET", "/bootconfigurations", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetBootConfiguration retrieves a specific BootConfiguration by UID
func (c *Client) GetBootConfiguration(ctx context.Context, uid string) (*bootconfiguration.BootConfiguration, error) {
	var result bootconfiguration.BootConfiguration
	endpoint := fmt.Sprintf("/bootconfigurations/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateBootConfiguration creates a new BootConfiguration
func (c *Client) CreateBootConfiguration(ctx context.Context, req CreateBootConfigurationRequest) (*bootconfiguration.BootConfiguration, error) {
	var result bootconfiguration.BootConfiguration
	if err := c.doRequest(ctx, "POST", "/bootconfigurations", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateBootConfiguration updates an existing BootConfiguration
func (c *Client) UpdateBootConfiguration(ctx context.Context, uid string, req UpdateBootConfigurationRequest) (*bootconfiguration.BootConfiguration, error) {
	var result bootconfiguration.BootConfiguration
	endpoint := fmt.Sprintf("/bootconfigurations/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteBootConfiguration deletes a BootConfiguration by UID
func (c *Client) DeleteBootConfiguration(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/bootconfigurations/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetNodes retrieves all nodes
func (c *Client) GetNodes(ctx context.Context) ([]node.Node, error) {
	var response []node.Node
	if err := c.doRequest(ctx, "GET", "/nodes", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetNode retrieves a specific Node by UID
func (c *Client) GetNode(ctx context.Context, uid string) (*node.Node, error) {
	var result node.Node
	endpoint := fmt.Sprintf("/nodes/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateNode creates a new Node
func (c *Client) CreateNode(ctx context.Context, req CreateNodeRequest) (*node.Node, error) {
	var result node.Node
	if err := c.doRequest(ctx, "POST", "/nodes", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateNode updates an existing Node
func (c *Client) UpdateNode(ctx context.Context, uid string, req UpdateNodeRequest) (*node.Node, error) {
	var result node.Node
	endpoint := fmt.Sprintf("/nodes/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteNode deletes a Node by UID
func (c *Client) DeleteNode(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/nodes/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
