// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Cobra-based CLI for the boot_service API.
// Generated from: pkg/codegen/templates/client-cmd.go.tmpl
//
// To modify the CLI:
//  1. Edit the template file: pkg/codegen/templates/client-cmd.go.tmpl
//  2. Run 'make generate-client-cmd' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated commands for each resource:
//   - client bootconfiguration [list|get|create|update|delete]
//   - client node [list|get|create|update|delete]
//
// Global flags (available for all commands):
//
//	--server       Server URL (env: BOOT_SERVICE_SERVER)
//	--timeout      Request timeout (env: BOOT_SERVICE_TIMEOUT)
//	--output, -o   Output format: table, json, yaml (env: BOOT_SERVICE_OUTPUT)
//	--version, -v  API version to request: v1, v2beta1, etc. (env: BOOT_SERVICE_VERSION)
//	--config       Config file path (default: ~/.boot_service-cli.yaml)
//
// Configuration sources (in order of precedence):
//  1. Command-line flags
//  2. Environment variables (BOOT_SERVICE_*)
//  3. Config file (~/.boot_service-cli.yaml)
//  4. Default values
//
// Usage examples:
//
//	# List all bootconfigurations (default version)
//	client bootconfiguration list
//
//	# List bootconfigurations with specific version
//	client bootconfiguration list --version v2beta1
//
//	# Get BootConfiguration as v1
//	client bootconfiguration get <uid> --version v1
//
//	# Create from JSON file with version
//	cat bootconfiguration.json | client bootconfiguration create --version v2beta1
//
//	# Create from inline JSON
//	client bootconfiguration create --spec '{"name":"bootconfiguration-01","description":"Example BootConfiguration"}'
//
//	# Use environment variables
//	export BOOT_SERVICE_SERVER=https://boot_service.example.com
//	export BOOT_SERVICE_VERSION=v2beta1
//	client bootconfiguration list
//
// To add custom commands:
//  1. Add command definition in template after resource commands
//  2. Register it in init() function
//
// To change output formatting:
//  1. Modify printOutput function to add new formats
//  2. Update output flag validation
//
// To add authentication:
//  1. Add auth flags (--token, --username, etc.)
//  2. Modify getClient to configure auth in http.Client
//  3. Add auth headers in client package
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/openchami/boot-service/pkg/client"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	cfgFile    string
	serverURL  string
	timeout    time.Duration
	output     string
	apiVersion string
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   filepath.Base(os.Args[0]),
	Short: "boot_service CLI",
	Long:  `A command-line interface for managing boot_service resources.`,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.boot_service-cli.yaml)")
	rootCmd.PersistentFlags().StringVar(&serverURL, "server", "http://localhost:8080", "boot_service server URL")
	rootCmd.PersistentFlags().DurationVar(&timeout, "timeout", 30*time.Second, "request timeout")
	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "table", "output format: table, json, yaml")
	rootCmd.PersistentFlags().StringVarP(&apiVersion, "version", "v", "", "API version to request (e.g., v1, v2beta1)")

	// Bind flags to viper
	viper.BindPFlag("server", rootCmd.PersistentFlags().Lookup("server"))
	viper.BindPFlag("timeout", rootCmd.PersistentFlags().Lookup("timeout"))
	viper.BindPFlag("output", rootCmd.PersistentFlags().Lookup("output"))
	viper.BindPFlag("version", rootCmd.PersistentFlags().Lookup("version"))

	// Environment variable support
	viper.SetEnvPrefix("BOOT_SERVICE")
	viper.AutomaticEnv()

	// Add resource commands
	rootCmd.AddCommand(bootconfigurationCmd)
	rootCmd.AddCommand(nodeCmd)

}

func initConfig() {
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			return
		}

		viper.AddConfigPath(home)
		viper.SetConfigType("yaml")
		viper.SetConfigName(".boot_service-cli")
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}

func getClient() (*client.Client, error) {
	serverURL := viper.GetString("server")
	c, err := client.NewClient(serverURL, nil)
	if err != nil {
		return nil, err
	}

	// Apply version if specified
	version := viper.GetString("version")
	if version != "" {
		c = c.WithVersion(version)
	}

	return c, nil
}

func printOutput(data interface{}) error {
	switch output {
	case "json":
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	case "yaml":
		// TODO: Add YAML support if needed
		return fmt.Errorf("YAML output not yet implemented")
	case "table":
		// Simple table output
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	default:
		return fmt.Errorf("unknown output format: %s", output)
	}
}

// BootConfiguration commands
var bootconfigurationCmd = &cobra.Command{
	Use:   "bootconfiguration",
	Short: "Manage bootconfigurations",
	Long:  `Create, read, update, and delete bootconfigurations.`,
}

var bootconfigurationListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all bootconfigurations",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetBootConfigurations(ctx)
		if err != nil {
			return fmt.Errorf("failed to list bootconfigurations: %w", err)
		}

		return printOutput(items)
	},
}

var bootconfigurationGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a BootConfiguration by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetBootConfiguration(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get BootConfiguration: %w", err)
		}

		return printOutput(item)
	},
}

var bootconfigurationCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new BootConfiguration",
	Long: `Create a new BootConfiguration.

Examples:
  # Create from stdin
  echo '{"hosts": ["["item1","item2"]"], "macs": ["["item1","item2"]"], "nids": [], "groups": ["["item1","item2"]"], "kernel": "example-value", "initrd": "example-value", "params": "example-value", "priority": 42}' | client bootconfiguration create

  # Create with --spec flag
  client bootconfiguration create --spec '{"hosts": ["["item1","item2"]"], "macs": ["["item1","item2"]"], "nids": [], "groups": ["["item1","item2"]"], "kernel": "example-value", "initrd": "example-value", "params": "example-value", "priority": 42}'

Spec fields:
  hosts ([]string)
  macs ([]string)
  nids ([]int32)
  groups ([]string)
  kernel (string)
  initrd (string)
  params (string)
  priority (int)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateBootConfigurationRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateBootConfiguration(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create BootConfiguration: %w", err)
		}

		return printOutput(item)
	},
}

var bootconfigurationUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing BootConfiguration",
	Long: `Update an existing BootConfiguration.

Examples:
  # Update from stdin
  echo '{"hosts": ["["item1","item2"]"], "macs": ["["item1","item2"]"], "nids": [], "groups": ["["item1","item2"]"], "kernel": "example-value", "initrd": "example-value", "params": "example-value", "priority": 42}' | client bootconfiguration update <uid>

  # Update with --spec flag
  client bootconfiguration update <uid> --spec '{"hosts": ["["item1","item2"]"], "macs": ["["item1","item2"]"], "nids": [], "groups": ["["item1","item2"]"], "kernel": "example-value", "initrd": "example-value", "params": "example-value", "priority": 42}'

Spec fields:
  hosts ([]string)
  macs ([]string)
  nids ([]int32)
  groups ([]string)
  kernel (string)
  initrd (string)
  params (string)
  priority (int)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateBootConfigurationRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateBootConfiguration(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update BootConfiguration: %w", err)
		}

		return printOutput(item)
	},
}

var bootconfigurationDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a BootConfiguration",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteBootConfiguration(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete BootConfiguration: %w", err)
		}

		fmt.Printf("BootConfiguration %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	bootconfigurationCmd.AddCommand(bootconfigurationListCmd)
	bootconfigurationCmd.AddCommand(bootconfigurationGetCmd)
	bootconfigurationCmd.AddCommand(bootconfigurationCreateCmd)
	bootconfigurationCmd.AddCommand(bootconfigurationUpdateCmd)
	bootconfigurationCmd.AddCommand(bootconfigurationDeleteCmd)

	// Add spec flag for create and update commands
	bootconfigurationCreateCmd.Flags().String("spec", "", "BootConfiguration specification in JSON format")
	bootconfigurationUpdateCmd.Flags().String("spec", "", "BootConfiguration specification in JSON format")
}

// Node commands
var nodeCmd = &cobra.Command{
	Use:   "node",
	Short: "Manage nodes",
	Long:  `Create, read, update, and delete nodes.`,
}

var nodeListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all nodes",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetNodes(ctx)
		if err != nil {
			return fmt.Errorf("failed to list nodes: %w", err)
		}

		return printOutput(items)
	},
}

var nodeGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a Node by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetNode(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new Node",
	Long: `Create a new Node.

Examples:
  # Create from stdin
  echo '{"xname": "example-name", "nid": 42, "bootMac": "example-value", "role": "example-value", "subRole": "example-value", "hostname": "example-name", "groups": ["["item1","item2"]"]}' | client node create

  # Create with --spec flag
  client node create --spec '{"xname": "example-name", "nid": 42, "bootMac": "example-value", "role": "example-value", "subRole": "example-value", "hostname": "example-name", "groups": ["["item1","item2"]"]}'

Spec fields:
  xname (string)
  nid (int32)
  bootMac (string)
  role (string)
  subRole (string)
  hostname (string)
  groups ([]string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateNodeRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateNode(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing Node",
	Long: `Update an existing Node.

Examples:
  # Update from stdin
  echo '{"xname": "example-name", "nid": 42, "bootMac": "example-value", "role": "example-value", "subRole": "example-value", "hostname": "example-name", "groups": ["["item1","item2"]"]}' | client node update <uid>

  # Update with --spec flag
  client node update <uid> --spec '{"xname": "example-name", "nid": 42, "bootMac": "example-value", "role": "example-value", "subRole": "example-value", "hostname": "example-name", "groups": ["["item1","item2"]"]}'

Spec fields:
  xname (string)
  nid (int32)
  bootMac (string)
  role (string)
  subRole (string)
  hostname (string)
  groups ([]string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateNodeRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateNode(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a Node",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteNode(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete Node: %w", err)
		}

		fmt.Printf("Node %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	nodeCmd.AddCommand(nodeListCmd)
	nodeCmd.AddCommand(nodeGetCmd)
	nodeCmd.AddCommand(nodeCreateCmd)
	nodeCmd.AddCommand(nodeUpdateCmd)
	nodeCmd.AddCommand(nodeDeleteCmd)

	// Add spec flag for create and update commands
	nodeCreateCmd.Flags().String("spec", "", "Node specification in JSON format")
	nodeUpdateCmd.Flags().String("spec", "", "Node specification in JSON format")
}
